// Writes src/app/core/build-info.ts (gitignored) from package.json + git.
// Bump the version with: npm version patch | minor | major
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

const { version } = JSON.parse(readFileSync('package.json', 'utf8'));
let commit = process.env.GITHUB_SHA?.slice(0, 7) ?? '';
if (!commit) {
  try {
    commit = execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch {
    commit = 'local';
  }
}

const info = { version, commit, builtAt: new Date().toISOString() };
writeFileSync(
  'src/app/core/build-info.ts',
  `// Generated by scripts/build-info.mjs. Do not edit.\nexport const BUILD_INFO = ${JSON.stringify(info, null, 2)} as const;\n`,
);
console.log(`build ${version} (${commit})`);
